stages:
  - sync

sync_job:
  stage: sync
  script:
    - git config --global credential.helper store
    - echo "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@gitlab.com" > ~/.git-credentials
    - git clone --mirror https://github.com/Pankaj-Kamate/osn-project.git osn-project
    - cd osn-project
    - git remote add gitlab https://gitlab.com/cicd-project-group1/osn-project.git
    - git push gitlab main

# last step in the pipeline to report status
# using CI_JOB_STATUS requires a more modern gitlab runner as in my lab
# using webhook instead
#notify:
#  image: ${DOCKER_REPO}/${RUNNER_IMAGE}
#  stage: .post
#  script:
#    - pip install webexteamssdk
#    # assumes teams token is provided in environment variable
#    # WEBEX_API_NOTIFICATION_TOKEN
#    - python scripts/notify.py "Pipeline result $CI_JOB_STATUS ($CI_JOB_URL)"
