name: Syncs to GitLabs

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.name "Pankaj-Kamate"
        git config --global user.email "pankajkamate@gmail.com"

    - name: Fetch from GitLab and Integrate
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.com/cicd-project-group1/project-nso.git

    - name: Push to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git push gitlab main
